POST http://localhost:3003/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11ayIsImlkIjoiNjRhY2NhNDBiMWNkMTA1NGQwYWU1YjNhIiwiaWF0IjoxNjg5MDQ1NTgyfQ.7l5zteH_1hUhrnny_29kbvhcrRVbpRULVXml2R-T3TU

{
    "title": "Tewdasdasdstqwdqdasdasdasdaddqwd blog",
    "author":  "mdqwdqwde",
    "url": "url",
    "likes": 69
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "salainen"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "muk",
    "name": "Matti",
    "password": "123"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "muk",
    "password": "123"
}


###
DELETE http://localhost:3003/api/blogs/64acca60b1cd1054d0ae5b43
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11ayIsImlkIjoiNjRhY2NhNDBiMWNkMTA1NGQwYWU1YjNhIiwiaWF0IjoxNjg5MDQ1NTgyfQ.7l5zteH_1hUhrnny_29kbvhcrRVbpRULVXml2R-T3TU

{
}